name: Update Translations
on:
  push:
    branches:
      - develop
    paths:
      - 'lang/*.json'
jobs:
  translations:
    if: github.repository_owner == 'Miskatonic-Investigative-Society'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          node generate-translations.js
          npm run format
      - run: |
          git config user.name 'snap01'
          git config user.email '43982555+snap01@users.noreply.github.com'
          git add .github/TRANSLATIONS.md
          git commit -m "Updated translations list"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
